### PR TITLE
add separate docs for each report section

### LINKED ISSUE #29: Setup branch, directory, and files for #28
**Describe what needs to get done**
Create a branch, directory, and files for each section of the requirements report #28

### PR DESCRIPTION
**Pull request by vnajack**
Each document will be used for its respective section in the report, and then they will all be combined in the final PDF report.
Closes #29

### CODE REVIEW

**Comment by edouarde1** [comment]
Thanks for doing that, this will keep us organized for when the report is due

**Review by LoganParker — APPROVED** [review]
All looks good! Should be useful for providing us with a guideline in the future

**Comment by edouarde1** [comment]
Thanks for doing this.. It will keep us organized for when the report is due!

**Review by edouarde1 — APPROVED** [review]
Looks good!

**Pull request merged**
