### PR TITLE
new pull request template

### PR DESCRIPTION
**Pull request by edouarde1**
Created a new PR template!  

Each time someone submits a PR is should be as follows: 
1. Description of the purpose 
2. References to the issue (Do we need this ?)
3. A checklist for the PR requirements, may be helpful for planning and for PR review

### CODE REVIEW

**Review by LoganParker — CHANGES_REQUESTED** [review]
No linked issue - please link one for gitstats!

**Review by LoganParker — APPROVED** [review]
Looks great! Thanks for this, it'll be helpful for the future :)

**Review by vnajack — COMMENTED** [review]
I'm not sure if I fully understand the pull request template. Can we go over this in class tomorrow morning? It might just be the headers that are unclear to me...

**Comment by LoganParker** [comment]
> I'm not sure if I fully understand the pull request template. Can we go over this in class tomorrow morning? It might just be the headers that are unclear to me...

The headers in the report? We can convert this to a normal pull request now, and then start a review if you'd like.

**Review by vnajack — APPROVED** [review]
I might not use as many emotes, but I like the checklists

**Comment by LoganParker** [comment]
@edouarde1 Don't forget to merge this!

**Pull request merged**
